name: Telegram Reminder

on:
  schedule:
    - cron: '30 11 * * *'   # 18:30 WIB = 11:30 UTC
    - cron: '45 12 * * *'   # 19:45 WIB = 12:45 UTC
    - cron: '0 15 * * *'    # 20:00 WIB = 13:00 UTC
    - cron: '0 23 * * *'    # 06:00 WIB = 23:00 UTC (hari sebelumnya UTC)

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Reminder 18:30
        if: github.event.schedule == '30 11 * * *'
        run: |
          curl -v -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.CHAT_ID }} \
          -d message_thread_id=14 \
          -d text="Blossoms! Jangan lupa ikut Kontes Bakat ya!! Login yuk!"

      - name: Reminder 19:45
        if: github.event.schedule == '45 12 * * *'
        run: |
          curl -v -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.CHAT_ID }} \
          -d message_thread_id=14 \
          -d text="Yuk cek Kontes sekarang dan klaim telur paskahnya!! Buruan keburu abis!"

      - name: Reminder 20:00
        if: github.event.schedule == '0 15 * * *'
        run: |
          curl -v -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.CHAT_ID }} \
          -d message_thread_id=14 \
          -d text="Blossoms!!"

      - name: Reminder 06:00
        if: github.event.schedule == '0 23 * * *'
        run: |
          curl -v -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.CHAT_ID }} \
          -d message_thread_id=14 \
          -d text="Pagi Blossoms! hari yang cerah, jangan lupa klaim harian!"
