name: Telegram Reminder Test

on:
  schedule:
    - cron: '*/5 * * * *'   # jalan tiap 5 menit sekali

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Test message
        run: |
          curl -v -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.CHAT_ID }} \
          -d message_thread_id=14 \
          -d text="Ini pesan test otomatis tiap 5 menit"
